Repository PFratt/Co-Operation-soen341project2023, pull requests merged in 2023-02, with the labels that each got.

#13 #7: Added project description, scrum master role, and reformatted readme
  README.md
Labels: documentation, Task

#21 Update README.md
  README.md
Labels: documentation, Task

#24 Update README.md
  README.md
Labels: Task

#47 Created JobApplication Component
  career-service-webapp/package-lock.json
  career-service-webapp/src/candidatePage/CandidatePage.jsx
  career-service-webapp/src/candidatePage/JobApplication.jsx
Labels: Frontend

#48 Application Status Component
  career-service-webapp/src/candidatePage/ApplicationStatus.jsx
  career-service-webapp/src/candidatePage/CandidatePage.jsx
Labels: User Story, Frontend

#49 Cleaned up styling
  career-service-webapp/src/candidatePage/ApplicationStatus.jsx
  career-service-webapp/src/candidatePage/JobApplication.jsx
  career-service-webapp/src/candidatePage/css/Candidate.css
Labels: Frontend

#52 Apply Now Button
  career-service-webapp/src/candidatePage/CandidatePage.jsx
  career-service-webapp/src/candidatePage/JobApplication.jsx
Labels: User Story, Frontend

#55 Backend REST-API with self-signed https
  .gitignore
  api.js
  code.crt
  code.csr
  code.key
  package-lock.json
  package.json
Labels: Backend

#59 JobApplication, JobPosting, Refactoring
  career-service-webapp/src/candidatePage/ApplicationStatus.jsx
  career-service-webapp/src/candidatePage/CandidatePage.jsx
  career-service-webapp/src/candidatePage/JobApplication.jsx
  career-service-webapp/src/candidatePage/JobPosting.jsx
  career-service-webapp/src/candidatePage/css/Candidate.css
Labels: Frontend

#61 Candidate Profile Component
  career-service-webapp/src/candidatePage/CandidatePage.jsx
  career-service-webapp/src/candidatePage/CandidateProfile.jsx
  career-service-webapp/src/candidatePage/JobApplication.jsx
  career-service-webapp/src/candidatePage/css/Candidate.css
Labels: Frontend
